# Generated by Django 6.0.5 on 2026-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_approved_review_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug, e.g. 'gwalior-to-delhi-cab'. Becomes the page URL.", max_length=200, unique=True)),
                ('title', models.CharField(help_text="HTML <title> tag. Include target keyword. E.g. 'Gwalior to Delhi Cab — ₹3500 One-Way | Manjari Taxi'", max_length=200)),
                ('meta_description', models.TextField(help_text='SEO meta description (aim for 150-160 characters).', max_length=300)),
                ('h1_heading', models.CharField(help_text='Main H1 heading on the page.', max_length=200)),
                ('intro_text', models.TextField(help_text='2-3 paragraphs of unique content for the hero area. Supports basic HTML.')),
                ('body_text', models.TextField(blank=True, default='', help_text='Additional body content below the hero. Supports basic HTML.')),
                ('distance_km', models.PositiveIntegerField(blank=True, help_text='Distance in kilometers, e.g. 321', null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate travel time in hours, e.g. 5.5', max_digits=4, null=True)),
                ('starting_price', models.PositiveIntegerField(blank=True, help_text='Starting fare in INR, e.g. 3500', null=True)),
                ('faq_json', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."} objects for FAQ schema.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published pages are visible on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route Page',
                'verbose_name_plural': 'Route Pages',
                'db_table': 'core_routepage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='core_review',
        ),
        migrations.AlterModelTable(
            name='service',
            table='core_service',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='core_vehicle',
        ),
    ]
