# Generated by Django 6.0.5 on 2026-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_routepage_alter_review_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='feature3',
        ),
        migrations.AddField(
            model_name='service',
            name='bullet_points',
            field=models.JSONField(default=list, help_text='List of bullet points to display on the service card'),
        ),
        migrations.AddField(
            model_name='service',
            name='css_class',
            field=models.CharField(blank=True, help_text='CSS class for the service card, e.g. "airport-card"', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Raw SVG code for the service icon'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(default=list, help_text='List of features, e.g. ["AC", "Luggage Space", "Music System"]'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
