# Generated by Django 6.0.5 on 2026-06-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings_booking',
        ),
    ]
